default: &default
  adapter: postgresql
  encoding: unicode
  database: developer_search
  username: postgres
  password: sunrise7793
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
